src/Entity/CmsLayoutRow.php
<?php

namespace Kisphp\CmsBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Kisphp\Entity\KisphpEntityInterface;
use Kisphp\Entity\ToggleableInterface;
use Kisphp\Utils\Status;

/**
 * @ORM\Entity
 * @ORM\Table(name="cms_layout_row", options={"colate": "utf8_general_ci", "charset": "utf8"})
 */
class CmsLayoutRow implements KisphpEntityInterface, ToggleableInterface
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"unsigned": true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true, options={"unsigned": true})
     */
    protected $id_parent;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true, options={"default": 1000})
     */
    protected $position;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"default": Kisphp\Utils\Status::ACTIVE})
     */
    protected $status = Status::ACTIVE;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", options={"unsigned": true})
     */
    protected $id_layout;

    /**
     * @ORM\ManyToOne(targetEntity="CmsLayout", inversedBy="rows")
     * @ORM\JoinColumn(name="id_layout", referencedColumnName="id")
     */
    protected $layout;

    /**
     * @ORM\ManyToOne(targetEntity="CmsLayoutRow")
     * @ORM\JoinColumn(name="id_parent", referencedColumnName="id")
     */
    protected $parent;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, options={"default": ""})
     */
    protected $title = '';

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=64, options={"default": ""})
     */
    protected $cssClass = '';

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=64, options={"default": ""})
     */
    protected $cssId = '';

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=128, options={"default": ""})
     */
    protected $type = '';

    /**
     * @ORM\OneToMany(targetEntity="CmsLayoutColumn", mappedBy="row", cascade={"persist", "remove"})
     */
    protected $columns;

    public function __construct()
    {
        $this->columns = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return 'CMS Row: ' . $this->getId();
    }

    /**
     * @return int
     */
    public function getIdParent(): int
    {
        return $this->id_parent;
    }

    /**
     * @param int $id_parent
     */
    public function setIdParent($id_parent)
    {
        $idParent = (int) $id_parent;

        if (!is_numeric($idParent) || $idParent < 1) {
            $idParent = null;
        }

        $this->id_parent = $idParent;
    }

    /**
     * @return mixed
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @param mixed $parent
     */
    public function setParent($parent): void
    {
        $this->parent = $parent;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = (int) $id;
    }

    /**
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * @param int $position
     */
    public function setPosition($position)
    {
        $this->position = $position;
    }

    /**
     * @return mixed
     */
    public function getIdLayout()
    {
        return $this->id_layout;
    }

    /**
     * @param mixed $id_layout
     */
    public function setIdLayout($id_layout)
    {
        $this->id_layout = $id_layout;
    }

    /**
     * @return mixed
     */
    public function getLayout()
    {
        return $this->layout;
    }

    /**
     * @param mixed $layout
     */
    public function setLayout(CmsLayout $layout)
    {
        $this->layout = $layout;
        $this->id_layout = $layout->getId();
    }

    /**
     * @return mixed
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * @param mixed $columns
     */
    public function setColumns($columns)
    {
        $this->columns = $columns;
    }

    /**
     * @param CmsLayoutColumn $column
     */
    public function addColumn(CmsLayoutColumn $column)
    {
        $this->columns->add($column);
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * @return string
     */
    public function getCssClass()
    {
        return $this->cssClass;
    }

    /**
     * @param string $cssClass
     */
    public function setCssClass($cssClass)
    {
        $this->cssClass = $cssClass;
    }

    /**
     * @return string
     */
    public function getCssId()
    {
        return $this->cssId;
    }

    /**
     * @param string $cssId
     */
    public function setCssId($cssId)
    {
        $this->cssId = $cssId;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }
}

src/Controller/CmsController.php
<?php

namespace Kisphp\CmsBundle\Controller;

use Kisphp\Entity\KisphpEntityInterface;
use Kisphp\FrameworkAdminBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class CmsController extends AbstractController
{
    const UPLOAD_TYPE = 'widget';

    /**
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function deleteColumnAction(Request $request)
    {
        $id = $request->request->getInt('id');

        $columnModel = $this->get('model.cms.layout')->getColumnModel();
        /** @var KisphpEntityInterface $entity */
        $entity = $columnModel->find($id);

        if ($entity === null) {
            return new JsonResponse([
                'code' => Response::HTTP_NOT_FOUND,
            ]);
        }

        $columnModel->remove($entity);

        return new JsonResponse([
            'code' => Response::HTTP_OK,
            'objectId' => $id,
        ]);
    }

    /**
     * @param int $id
     *
     * @return KisphpEntityInterface
     */
    protected function createFormEntity($id)
    {
        $model = $this->get(static::MODEL_NAME);

        $object = $model->find($id);
        if (empty($object)) {
            $object = $model->createEntity();
        }

        return $object;
    }

    /**
     * @param int $id
     *
     * @return \Kisphp\CmsBundle\Entity\CmsLayout|\Kisphp\Entity\KisphpEntityInterface
     */
    protected function createEntityObject($id)
    {
        /** @var \Kisphp\CmsBundle\Entity\CmsLayout $object */
        $object = $this->createFormEntity($id);

        $layoutModel = $this->get('model.cms.layout');

        $rows = $object->getRows();
        if (count($rows) < 1) {
            $column = $layoutModel->getColumnModel()->createEntity();
            $row = $layoutModel->getRowModel()->createEntity();
            $column->setRow($row);
            $row->setLayout($object);
            $row->addColumn($column);
            $object->addRow($row);
        }

        return $object;
    }

    /**
     * @param int $id
     *
     * @return string
     */
    protected function getImagesEditUrl($id)
    {
        return $this->generateUrl('adm_cms_widget_attached', [
            'id' => $id,
        ]);
    }

    /**
     * @param int $articleId
     *
     * @return array
     */
    protected function getAttachedFiles($articleId)
    {
        $model = $this->get('model.media_files');

        return $model->findBy([
            'id_object' => $articleId,
            'object_type' => static::UPLOAD_TYPE,
        ]);
    }
}

src/Resources/views/Cms/cms-layout.html.twig
{% extends '@FrameworkAdmin/components/form.html.twig' %}

{% block box_header %}
    <a href="{{ path(section.list_path) }}" class="btn btn-xs btn-github"><i class="fa fa-list"></i> {{ 'btn.cms.layout.list' | trans }}</a>
    {% if section.add_path != '' %}
        <a href="{{ path(section.add_path) }}" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> {{ 'btn.cms.layout.create' | trans }}</a>
    {% endif %}
{% endblock %}

src/Resources/views/Cms/edit-layout.html.twig
{% extends '@Cms/Cms/cms-layout.html.twig' %}

{% block box_header %}
    {% if entity is defined and entity.id is defined and entity.id > 0 %}
        <a href="{{ path('adm_cms_layout_duplicate', {id: entity.id}) }}" class="btn btn-xs btn-default"><i class="fa fa-copy"></i> {{ 'btn.cms.layout.duplicate' | trans }}</a>
        <a href="{{ path('adm_cms_layout_view', {id: entity.id}) }}" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> {{ 'btn.view_widgets' | trans }}</a>
    {% endif %}
    {{ parent() }}
{% endblock %}

{% block body %}

    <form class="form-horizontal" method="post">

        <div class="col-xs-6 col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Layout settings</h3>
                </div>
                <div class="panel-body">
                    <input type="hidden" name="id" id="form_id" value="">
                    <div class="form-group">
                        <label for="form_page_title" class="col-sm-3 control-label">Layout Name</label>
                        <div class="col-sm-9">
                            <input type="text" id="form_page_title" class="form-control" placeholder="title" name="title" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="form_page_url" class="col-sm-3 control-label">Url</label>
                        <div class="col-sm-9">
                            <input type="text" id="form_page_url" class="form-control" placeholder="url" name="url" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">SEO</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label for="form_page_seo_title" class="col-sm-2 control-label">Title</label>
                        <div class="col-sm-10">
                            <input type="text" id="form_page_seo_title" class="form-control" placeholder="SEO Title" name="seo_title" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="form_page_seo_keywords" class="col-sm-2 control-label">Keywords</label>
                        <div class="col-sm-10">
                            <input type="text" id="form_page_seo_keywords" class="form-control" placeholder="SEO Keywords" name="seo_keywords" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="form_page_seo_description" class="col-sm-2 control-label">Description</label>
                        <div class="col-sm-10">
                            <textarea name="seo_description" id="form_page_seo_description" class="form-control" placeholder="SEO Description" cols="30" rows="5"></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="grid" class="grid_sortable"></div>

        <div class="col-xs-12 col-sm-6">
            <button class="btn btn-sm btn-success" name="save"><i class="fa fa-save"></i> Save</button>
        </div>
        <div class="col-xs-12 col-sm-6 text-right">
            <a href="#" id="row-add" class="btn btn-sm btn-info"><i class="fa fa-plus"></i> Add Row</a>
        </div>

    </form>

    <script id="row-tpl" type="text/template">
        <div class="col-xs-12 col-sm-12" id="row-{id}">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <input type="hidden" name="rows[{id}][id]" value="{id}" id="row-id-{id}">
                    <h3 class="panel-title">
                        <div class="row">
                            <div class="col-xs-9"><a href="#" class="remove-row text-danger" data-id="{id}"><i class="fa fa-trash"></i></a> Row: {title}</div>
                            <div class="col-xs-3 text-right">
                                <a href="#" data-row-id="{id}" class="add-column pull-right btn btn-xs btn-primary">Add column</a>
                            </div>
                        </div>
                    </h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Row title</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="rows[{id}][title]" value="{title}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Row Parent</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="rows[{id}][id_parent]" value="{id_parent}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Row type</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="rows[{id}][type]" value="{type}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Row CSS class</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="rows[{id}][css_class]" value="{css_class}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Row CSS id</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="rows[{id}][css_id]" value="{css_id}" />
                        </div>
                    </div>
                    <div id="columns-{id}"></div>
                </div>
            </div>
        </div>
    </script>

    <script id="col-tpl" type="text/template">
        <div class="form-group" id="column-{col}">
            <hr class="hr">
            <div class="col-sm-12">
                <label class="control-label">Column</label>
            </div>
            <div class="col-sm-12">
                <div>
                        {#<input type="hidden" name="rows[{row}][columns][{col}][id]" id="col-id-{col}" value="{col}">#}
                        {#<input type="text" name="rows[{row}][columns][{col}][attr_class]" class="form-control" value="{attr_class}" />#}
                        {#<div class="input-group-addon"><a href="#" class="remove-column" data-id="{col}"><i class="fa fa-trash text-danger"></i></a></div>#}
                    <label class="col-sm-3 control-label">Column title</label>
                    <div class="col-sm-9">
                        <div class="input-group">
                            <input type="text" class="form-control" name="rows[{row}][columns][{col}][title]" value="{title}" />
                            <div class="input-group-addon"><a href="#" class="remove-column" data-id="{col}"><i class="fa fa-trash text-danger"></i></a></div>
                        </div>
                    </div>
                </div>
                <div class="">
                    <label class="col-sm-3 control-label">Inherit Column</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" name="rows[{row}][columns][{col}][id_parent]" value="{id_parent}" />
                    </div>
                </div>
                <div class="">
                    <label class="col-sm-3 control-label">Column class</label>
                    <div class="col-sm-9">
                        <input type="hidden" name="rows[{row}][columns][{col}][id]" id="col-id-{col}" value="{col}">
                        <input type="text" name="rows[{row}][columns][{col}][attr_class]" class="form-control" value="{attr_class}" />
                    </div>
                </div>
            </div>
        </div>
    </script>

{% endblock %}

{% block js %}
    <script>
      {#let sortActionUrl = '{{ path('adm_cms_layout_row_sort') }}';#}
      let sortActionUrl = '';
      let formData = {{ formData | json_encode | raw }};
    </script>
    {{ parent() }}
{% endblock %}

src/Resources/views/Cms/edit-widget.html.twig
{% extends '@Cms/Cms/cms-layout.html.twig' %}

{% block box_header %}
    {% if entity.id > 0 %}
        <a href="{{ site_url }}/cms/{{ entity.column.row.layout.id }}" target="_blank" class="btn btn-xs btn-warning"><i class="fa fa-binoculars" aria-hidden="true"></i> {{ 'btn.preview_layout' | trans }}</a>
        <a href="#modal-move" data-toggle="modal" data-target="#modal-move" class="btn btn-xs btn-info"><i class="fa fa-arrows-alt"></i> {{ 'btn.cms.widget.move_to_row' | trans }}</a>
    {% endif %}
    <a href="{{ path('adm_cms_layout_view', {id: entity.column.row.idLayout}) }}" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> {{ 'btn.cms.widget.list' | trans }}</a>
    {% if entity.id > 0 %}
        <a href="{{ path('adm_cms_layout_add_widget', {column: entity.column.id}) }}" class="btn btn-xs btn-success"><i class="fa fa-plus"></i> {{ 'btn.cms.widget.create' | trans }}</a>
    {% endif %}
{% endblock %}

{% block body %}

    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

        {{ form_widget(form.widget) }}
        {% if form.content is defined %}
        {{ form_widget(form.content) }}
        {% endif %}

        <div class="box-footer">
            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <input type="submit" class="btn btn-success" value="{{ 'btn.save' | trans }}">
                </div>
            </div>
        </div>
    {{ form_end(form) }}

    {% if id > 0 and upload_type != '' %}
        {% include '@FrameworkAdmin/components/upload-images.html.twig' with { type: upload_type } %}
    {% endif %}

    <div class="modal fade" id="modal-move" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Move widget to different column</h4>
                </div>
                <div class="modal-body">
                    {% for row in layout.rows %}
                        <fieldset>
                            <legend>{{ row.title }}</legend>
                            <div class="row">
                                {% for col in row.columns %}
                                <div class="col-xs-{{ 12 / (row.columns | length) }}">
                                    <div class="bg-gray disabled" style="padding: 5px;">
                                        {% if col.id != entity.column.id %}
                                            <form action="{{ path('adm_cms_layout_widget_move') }}" method="post">
                                                <input type="hidden" name="column_id" value="{{ col.id }}" />
                                                <input type="hidden" name="widget_id" value="{{ entity.id }}" />
                                                <button class="btn btn-success btn-xs"><i class="fa fa-bullseye"></i> Move here</button>
                                            </form>
                                        {% else %}
                                        <button class="btn btn-default disabled btn-xs">From here</button>
                                        {% endif %}
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </fieldset>
                    {% endfor %}

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

{% endblock %}

{% block js %}
    {{ parent() }}
    <script>
      $( function() {
        let dateFormat = "yy-mm-dd";
        let from = $("#cms_layout_container_form_widget_date_start")
            .datepicker({
              defaultDate: "+1w",
              changeMonth: true,
              numberOfMonths: 3,
              dateFormat: dateFormat
            })
            .on("change", function() {
              to.datepicker("option", "minDate", getDate(this));
            });
        $( "#cms_layout_container_form_widget_date_stop" ).datepicker({
            defaultDate: "+1w",
            changeMonth: true,
            numberOfMonths: 3,
            dateFormat: dateFormat
        })
        .on("change", function() {
            from.datepicker("option", "maxDate", getDate(this));
        });

        function getDate(element) {
          let date;
          try {
            date = $.datepicker.parseDate(dateFormat, element.value);
          } catch( error ) {
            date = null;
          }

          return date;
        }
      } );
    </script>
{% endblock %}

src/Resources/views/Cms/index.html.twig
{% extends '@FrameworkAdmin/components/listing.html.twig' %}

{% import '@FrameworkAdmin/macros/navigation-macros.html.twig' as navBtn %}
{% import '@FrameworkAdmin/macros/table-btn-macros.html.twig' as tbl %}

{% block box_header %}
    {{ navBtn.list(path('adm_cms_template'), 'btn.cms.templates.list', 'fa-list', 'btn-info') }}
    {{ navBtn.list(path(section.list_path), 'btn.cms.layout.list') }}
    {{ navBtn.create(path(section.add_path), 'btn.cms.layout.create') }}
{% endblock %}

{% block listing_table_content %}
    <thead>
    <tr>
        <th width="200">{{ 'table.header.options' | trans }}</th>
        <th width="60">{{ 'table.header.id' | trans }}</th>
        <th>{{ 'table.header.title' | trans }}</th>
        <th>{{ 'table.header.url' | trans }}</th>
        <th width="60">{{ 'table.header.status' | trans }}</th>
    </tr>
    </thead>
    <tbody>
    {% for item in items %}
        <tr id="row-{{ item.id }}">
            <td>
                {{ tbl.edit(path(section.edit_path, {id: item.id})) }}
                {{ tbl.delete(item.id, path(section.delete_path)) }}
            </td>
            <td>{{ item.id }}</td>
            <td><a href="{{ path('adm_cms_layout_view', {id: item.id}) }}">{{ item.title }}</a></td>
            <td>{{ item.url }}</td>
            {{ statusToggle(item, path(section.status_path)) }}
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}

src/Resources/views/Cms/view-layout.html.twig
{% extends '@Cms/Cms/cms-layout.html.twig' %}

{% import '@FrameworkAdmin/macros/table-btn-macros.html.twig' as tbl %}

{% block box_header %}
    <a href="{{ site_url }}/cms/{{ entity.id }}" target="_blank" class="btn btn-xs btn-warning"><i class="fa fa-binoculars" aria-hidden="true"></i> {{ 'btn.preview_layout' | trans }}</a>
    <a href="{{ path('adm_cms_layout_edit', {id: entity.id}) }}" class="btn btn-xs btn-primary"><i class="fa fa-eye" aria-hidden="true"></i> {{ 'btn.edit_layout' | trans }}</a>
    {{ parent() }}
{% endblock %}

{% block body %}

    {% for rows in entity.rows %}

        <div class="row">
            <div class="col-sm-12">
                <h4>{{ rows.title }}</h4>
            </div>
            {% for col in rows.columns %}
            <div class="col-sm-{{ 12 / rows.columns | length | round(0, 'floor') }}">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-sm-6">
                                <h3 class="panel-title">Column: <b>[#{{ col.id }}] {{ col.title }}</b></h3>
                            </div>
                            {% if col.idParent < 1 %}
                            <div class="col-sm-6 text-right">
                                <a href="{{ path('adm_cms_layout_add_widget', {column: col.id}) }}" class="btn btn-xs btn-info"><i class="fa fa-plus"></i> {{ 'btn.cms.widget.create' | trans }}</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="panel-body">
                        {% if col.idParent > 0 %}
                        <p>This column inherit column: {{ col.idParent }}</p>
                        {% else %}
                        <table class="table table-bordered table-condensed">
                            <tbody class="sortable">
                                {% for wid in col.widgets %}
                                    {% if wid.status > 0 %}
                                    <tr id="row-{{ wid.id }}" class="droptrue">
                                        <td width="130">
                                            {{ tbl.edit(path('adm_cms_layout_edit_widget', {id: wid.id})) }}
                                            {{ tbl.delete(wid.id, path(section.delete_path)) }}
                                        </td>
                                        <td width="40" align="right">{{ wid.id }}</td>
                                        <td class="handle"><a href="{{ path('adm_cms_layout_edit_widget', {id: wid.id}) }}">{{ wid.title }}</a></td>
                                        <td width="30" align="center"><i class="fa fa-clock-o{% if wid.isChangeStatus == false %} disabled{% endif %}"></i></td>
                                        {{ statusToggle(wid, path('adm_cms_layout_widget_status')) }}
                                    </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>

    {% endfor %}

{% endblock %}

{% block js %}
    <script>
        let sortActionUrl = '{{ path('adm_cms_layout_widget_sort') }}';
    </script>
    {{ parent() }}
{% endblock %}